---
- name: Example Playbook
  hosts: web,db

  vars_files:
    - secrets.yml

  tasks:
    - name: Show encrypted web password
      debug:
        var: encrypted_web_password

    - name: Show encrypted db password
      debug:
        var: encrypted_db_password
