- hosts: web
# user: ubuntu
  tasks:
   - name: Create directory
     file:
       path: /etc/suman
       state: directory
    - name: Create user
      user:
        name: usersuman
        shell: /bin/bash
        uid: 6666
        comment: "my rh-aaap user "
        state: present
