- hosts: web
# user: ubuntu
  tasks:
   - name: Create directory
     file:
       path: "{{ dir_name }}"
       state: "{{ dir_state }}"
   - name: Create user
     user:
       name: usersuman
       shell: /bin/bash
       uid: 6666
       comment: "my rh-aaap user "
       state: "{{ user_state }}"
