---
- name: Secure Automation with Ansible Vault on Ubuntu
  hosts: db
  become: true
  gather_facts: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Debug current host and group
      debug:
        msg: "Running on host {{ inventory_hostname }} in group {{ group_names }}"

    - name: Show Encrypted Web Password (web group only)
      debug:
        var: encrypted_web_password
      when: "'web' in group_names"

    - name: Show Encrypted DB Password (db group only)
      debug:
        var: encrypted_db_password
      when: "'db' in group_names"

    - name: Ensure required packages are installed
      apt:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: pkg is defined

    - name: Create a user with vault password
      user:
        name: appuser
        password: "{{ (encrypted_web_password if 'web' in group_names else encrypted_db_password) }}"
        shell: /bin/bash
        state: present

    - name: Create application configuration file with credentials
      copy:
        dest: "/etc/app_secure.conf"
        content: |
          [credentials]
          user = appuser
          password = {{ encrypted_web_password if 'web' in group_names else encrypted_db_password }}
        owner: root
        group: root
        mode: '0600'

    - name: Ensure the application service is running (apache2 or mysql)
      service:
        name: "{{ 'apache2' if 'web' in group_names else 'mysql' }}"
        state: started
        enabled: true
