---
- name: Deploy web server - Deploy flask app
  hosts: "{{ environment }}"
  tasks:
    - name: Show environment and version
      debug:
        msg: "Deploying to {{ environment }} environment with version {{ version }}"
  roles:
    - roles/appserver
