---
- name: Example Playbook to see secrets
  hosts: web,app

  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Show encrypted web admin password
      debug:
        var: web_admin_password

    - name: Show encrypted db connection string
      debug:
        var: db_connection_string
