---
- name: Example Playbook to see secrets
  hosts: localhost

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Show encrypted web admin password
      debug:
        var: secrets.web_admin_password

    - name: Show encrypted db connection string
      debug:
        var: secrets.db_connection_string
